version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      # Insert the page access token
      PAGE_ACCESS_TOKEN: "EAAMUNHHPfWsBAFtScPZCqFBtRBGaf77YUBvNcYrF2N2FQ5rOavmZAjgLKUWtGRP9ePerbrEwXtA1n4qkKVGzFRicYSDHSk2qwTsePoXj3cPi307vk6i0iZBXY25NiZCNJs1qPqKF6DQltGCp1vk9KhZCAVcIHAaOkEQVxVmtNCwLk1HlP5VcVBbB3oaCWEZCcZD"
      # Insert the  PSID messenger
      PSID_BOSS: "3197739463674316"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results

      # Send notification to messenger
      - run:
          name: Sending notification
          when: on_success
          command: |
            if [[ true ]];  then
              curl -X POST -H  "Content-Type: application/json" -d \
                '{
                  "recipient":{
                    "id":"'$PSID_BOSS'"
                  },
                  "message":{
                    "text":"💚 💚 💚 \n Tạo PR ok rồi nhé! 🤑 💸  ! \n - Repository name: '$CIRCLE_PROJECT_USERNAME'/'$CIRCLE_PROJECT_REPONAME' \n - Author: '$CIRCLE_USERNAME' \n - Branch: '$CIRCLE_BRANCH' \n - Pull request:'$CIRCLE_PULL_REQUEST' \n - CI Detail: '$CIRCLE_BUILD_URL' "
                  }
                }' "https://graph.facebook.com/v2.6/me/messages?access_token=$PAGE_ACCESS_TOKEN"
            fi
      - run:
          name: Sending notification
          when: on_fail
          command: |
            if [[ true ]];  then
              curl -X POST -H  "Content-Type: application/json" -d \
                '{
                  "recipient":{
                    "id":"'$PSID_BOSS'"
                  },
                  "message":{
                    "text":" ❌ ❌ ❌  \n Lỗi rồi! Kiểm tra lại coi! 😨 😨 💔 ! \n - Repository name: '$CIRCLE_PROJECT_USERNAME'/'$CIRCLE_PROJECT_REPONAME' \n - Author: '$CIRCLE_USERNAME' \n - Branch: '$CIRCLE_BRANCH' \n - Pull request: '$CIRCLE_PULL_REQUEST' \n - CI Detail: '$CIRCLE_BUILD_URL' "
                  }
                }' "https://graph.facebook.com/v2.6/me/messages?access_token=$PAGE_ACCESS_TOKEN"
            fi
